# Install pre-commit hooks via
# pre-commit install

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: end-of-file-fixer
        exclude: &exclude_pre_commit_hooks >
            (?x)^(
                tests/.*(?<!\.py)$|
                docs/source/.+\.aiida/repo/.+|
            )$
    -   id: mixed-line-ending
    -   id: trailing-whitespace
        exclude: *exclude_pre_commit_hooks
    -   id: check-yaml

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: ^aiida_orca/parsers/cclib/
    -   id: ruff-format
        exclude: ^aiida_orca/parsers/cclib/

-   repo: local

    hooks:

    -   id: mypy
        name: mypy
        entry: mypy
        args: [--config-file=pyproject.toml]
        language: python
        types: [python]
        require_serial: true
        pass_filenames: true
        files: >-
            (?x)^(
                aiida_orca/calculations/orca_orca.py |
                aiida_orca/parsers/__init__.py |
                aiida_orca/utils/input_generator.py |
                aiida_orca/workchains/base.py |
                aiida_orca/inputs/.*\.py
            )$
