"""AiiDA-ORCA input generator"""

from copy import deepcopy


class OrcaInput:
    """Transforms dictionary into ORCA input"""

    def __init__(self, params):
        """Initializing OrcaInput object"""

        self._params = deepcopy(params)

    def render(self):
        output = ['### Generated by AiiDA-ORCA Plugin ###']
        self._render_input(output, deepcopy(self._params))
        return "\n".join(output)

    @staticmethod
    def _render_input(output, params):
        """
        Rendering differnt sections
        """
        #pylint: disable = too-many-branches
        if 'input_keywords' in params:
            keywords = params['input_keywords']
        else:
            keywords = {'SP': None}  # as a default

        if 'extra_input_keywords' in params:
            extra_keywords = params['extra_input_keywords']

        if 'input_blocks' in params:
            blocks = params['input_blocks']

        inp_keyword = "!"

        for key, value in keywords.items():
            if value is None:
                inp_keyword += " " + key
            else:
                inp_keyword += " " + key + '=' + str(value)

        output.append(inp_keyword)

        if extra_keywords:
            xtrainp_keyword = "!"
            for key, value in extra_keywords.items():
                if value is None:
                    xtrainp_keyword += " " + key

                else:
                    xtrainp_keyword += " " + key + '=' + str(value)

            output.append(xtrainp_keyword)

        b = ""  #pylint: disable = invalid-name
        if blocks:
            for key in blocks.keys():
                b += f"%{key} \n"  #pylint: disable = invalid-name
                for k, v in blocks[key].items():  #pylint: disable = invalid-name
                    b += "\t" + str(k) + " " + str(v) + "\n"  #pylint: disable = invalid-name
                b += "end\n"  #pylint: disable = invalid-name
        output.append(b)
        #     coordinate section
        c = "* xyzfile"  #pylint: disable = invalid-name
        c += f" {params['charge']} {params['multiplicity']} aiida.xyz\n"  #pylint: disable = invalid-name
        output.append(c)
