name: ci

on:
  pull_request:
  push:
    branches:
      - main

env:
  FORCE_COLOR: 1

jobs:

    pre-commit:

        runs-on: ubuntu-latest

        steps:
        -   uses: actions/checkout@v6

        -   name: Set up Python
            uses: actions/setup-python@v6
            with:
                python-version: '3.10'

        - name: Set up uv
          uses: astral-sh/setup-uv@v7
          with:
            python-version: ${{ matrix.python-version }}
            activate-environment: true

        -   name: Install Python dependencies
            run: uv pip install -e .[pre-commit,test]

        -   name: Run pre-commit
            run: pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )

    tests:

        runs-on: ubuntu-latest
        timeout-minutes: 10

        strategy:
            fail-fast: false
            matrix:
                versions: [
                    {'python': '3.9', 'aiida-core': '2.1.0'},
                    {'python': '3.10', 'aiida-core': '2.2.0'},
                    {'python': '3.11', 'aiida-core': '2.3.0'},
                    {'python': '3.12', 'aiida-core': '2.4.0'},
                ]

        services:
            postgres:
                image: postgres:12
            rabbitmq:
                image: rabbitmq:latest
                ports:
                -   5672:5672

        steps:
        -   uses: actions/checkout@v6

        -   name: Set up Python ${{ matrix.versions.python }}
            uses: actions/setup-python@v6
            with:
                python-version: ${{ matrix.versions.python }}

        - name: Set up uv
          uses: astral-sh/setup-uv@v7
          with:
            python-version: ${{ matrix.python-version }}
            activate-environment: true

        -   name: Install Python dependencies
            run: uv pip install -e .[test] aiida-core~=${{ matrix.versions.aiida-core }}

        -   name: Run pytest
            env:
                AIIDA_WARN_v3: True
            run: pytest --cov-report=xml --cov=./aiida_orca tests
        -   name: Upload coverage to codecov
            uses: codecov/codecov-action@v5
            with:
                token: ${{secrets.CODECOV_TOKEN}}
                file: ./coverage.xml
