name: ci

on: [push, pull_request]

jobs:

    quality:

        runs-on: ubuntu-latest

        steps:
        -   uses: actions/checkout@v4

        -   uses: ./.github/actions/setup-python-env

        -   name: Check uv.lock is up to date
            run: uv lock --locked

        -   name: Run ruff
            run: |
                uv run ruff check .
                uv run ruff format --check .

        -   name: Run mypy
            run: >
                uv run mypy
                aiida_orca/calculations/orca_orca.py
                aiida_orca/parsers/__init__.py
                aiida_orca/utils/input_generator.py
                aiida_orca/workchains/base.py

    tests:

        runs-on: ubuntu-latest
        timeout-minutes: 10

        strategy:
            fail-fast: false
            matrix:
                versions: [
                    {'python': '3.11', 'aiida-core': '2.1'},
                    {'python': '3.12', 'aiida-core': '2.1'},
                    {'python': '3.13', 'aiida-core': '2.1'},
                    {'python': '3.14', 'aiida-core': '2.1'},
                ]

        services:
            postgres:
                image: postgres:12
            rabbitmq:
                image: rabbitmq:latest
                ports:
                -   5672:5672

        steps:
        -   uses: actions/checkout@v4

        -   uses: ./.github/actions/setup-python-env
            with:
                python-version: ${{ matrix.versions.python }}

        -   name: Install aiida-core ${{ matrix.versions.aiida-core }}
            run: uv pip install "aiida-core~=${{ matrix.versions.aiida-core }}"

        -   name: Run pytest
            env:
                AIIDA_WARN_v3: True
            run: uv run pytest --cov-report=xml --cov=./aiida_orca tests

        -   name: Upload coverage to codecov
            uses: codecov/codecov-action@v4
            with:
                token: ${{secrets.CODECOV_TOKEN}}
                file: ./coverage.xml
